# NumPy
### 1. Array Creation and Manipulation

Create a NumPy array of shape (3, 3) filled with random integers. Replace all the elements in any row with 9.

In [24]:
import numpy as np

# np.random.randint(a,b,size=(c,d)) creates an array of random integers between a and b, endpoints inclusive, of dimensions (c,d)
array = np.random.randint(1, 10, size=(3, 3))
print("Original array:")
print(array)

# replacing the elements in 2nd row with 9
array[1] = 9
# or use Array[1,:] = 9
print("Modified array:")
print(array)

Original array:
[[2 6 6]
 [8 3 3]
 [4 4 8]]
Modified array:
[[2 6 6]
 [9 9 9]
 [4 4 8]]


Create a NumPy array of shape (3, 3) with values from 1 to 10. Replace the diagonal elements with 0.

In [22]:

# np.arange(a,b,c) returns an array of integers from a-b ordered, with a step of c
# a similar way would be using range(a,b,c), converting to list, converting to array 
array = np.arange(1, 19,2).reshape([3,3])     # can also use arr.reshape(3,3), same functionality


print("Original array:")
print(array)

# Replacing the diagonal with np.fill_diagonal(array,x) function
# Fills the diagonal of given array with x
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Modified array:
[[ 0  3  5]
 [ 7  0 11]
 [13 15  0]]


### 2. Array Indexing and Slicing

Create a 2d NumPy array. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [ ]:

array = np.arange(1, 50).reshape(7, 7)
print("Original array:")
print(array)

# Extract the sub-array
# indexing in array 
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
Sub-array:
[[16 17 18]
 [23 24 25]
 [30 31 32]]


Create a NumPy array of any shape with random floats upto 2 decimals. Extract bordering elements.

In [31]:
# another way to create arrays with random integers/floating points is using list comprehension, then array conversion
# round(a,b) rounds the number a to b decimal places
# another way of limit decimals is truncation,  math.trunc(a) removes the decimal entirely

import random

array = np.array([round(random.uniform(1,10),2) for x in range(32)]).reshape(4,8)
print("Original array:")
print(array)

# Extract the elements on the border, this code will work for all 2d arrays
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Bordering elements:")
print(border_elements)

Original array:
[[2.37 4.62 2.52 1.58 3.83 8.45 2.24 9.5 ]
 [6.3  3.73 7.61 3.01 7.66 2.63 4.32 9.01]
 [3.78 8.32 2.34 9.48 8.43 9.14 3.57 2.44]
 [6.41 5.39 8.06 3.84 3.72 6.15 8.39 1.98]]
Bordering elements:
[2.37 4.62 2.52 1.58 3.83 8.45 2.24 9.5  6.41 5.39 8.06 3.84 3.72 6.15
 8.39 1.98 6.3  3.78 9.01 2.44]


### 3. Array Operations

Create two NumPy arrays of same shapes. Perform basic vector/array operations.

In [38]:

array1 = np.array([random.randint(1,10) for x in range(6)]).reshape(2,3)
array2 = np.array([random.randint(1,10) for x in range(6)]).reshape(2,3)
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)


print('element wise operations')
print("addition:")
print(array1 + array2)
print("subtraction:")
print(array1 - array2)
print("multiplication:")
print(array1 * array2)
print("division:")
print(array1 / array2)
print("floor division:")
print(array1 // array2)
print("remainders:")
print(array1 % array2)



Array 1:
[[2 6 7]
 [5 7 1]]
Array 2:
[[4 6 5]
 [2 2 4]]
element wise operations
addition:
[[ 6 12 12]
 [ 7  9  5]]
subtraction:
[[-2  0  2]
 [ 3  5 -3]]
multiplication:
[[ 8 36 35]
 [10 14  4]]
division:
[[0.5  1.   1.4 ]
 [2.5  3.5  0.25]]
floor division:
[[0 1 1]
 [2 3 0]]
remainders:
[[2 0 2]
 [1 1 1]]


Create a NumPy array. Compute the row-wise and column-wise sum.

In [42]:
array = np.arange(1, 16).reshape((3, 5))
print("Original array:")
print(array)


print("Row-wise sum:")
print(np.sum(array, axis=1))
print("Column-wise sum:")
print(np.sum(array, axis=0))

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Row-wise sum:
[15 40 65]
Column-wise sum:
[18 21 24 27 30]


### 4. Statistical Operations

Compute the mean, median, standard deviation, and variance of an array.

In [43]:
array = np.random.randint(1, 21, size=(4, 4))
print(array)

# standard statistics, easily applied functions, builtin numpy
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

[[11  4 18 10]
 [ 5 16  2 10]
 [15 17 15 18]
 [ 7  6 12 13]]
Mean: 11.1875
Median: 11.5
Standard Deviation: 5.027657879171971
Variance: 25.27734375


Normalize a numpy array.

In [46]:
# normalize -  scale the values to have a mean of 0 and a standard deviation of 1

array = np.arange(1, 10).reshape((3, 3))
print('array', array)

# Normalizing, can find this formula in statistics
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### 5. Broadcasting

Create a NumPy array filled with random integers. Add a 1D array to each row of the 2D array using broadcasting.

In [64]:

array = np.random.randint(1, 11, size=(3, 4))
# if creating a 1d array, we dont have to put size inside parethesis
row_array = np.random.randint(1, 11, size=4)
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 1  6  9  2]
 [10  6  7  5]
 [ 1  8  7 10]]
1D array:
[10  5  5  3]
Resulting array:
[[11 11 14  5]
 [20 11 12  8]
 [11 13 12 13]]


Create a NumPy array. Subtract a 1D array of shape 4 from each column of the 2D array using broadcasting.

In [68]:
array = np.random.randint(1, 11, size=(4, 8))
column_array = np.random.randint(1, 11, size=4)
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtraction columnwise
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 6  5  1  6  1 10  1  2]
 [ 1  3  6  6  3  8  1  2]
 [ 1 10  7  4  8  1 10  6]
 [ 9  7  6  9  5  5  6  1]]
1D array:
[3 9 6 2]
Resulting array:
[[ 3  2 -2  3 -2  7 -2 -1]
 [-8 -6 -3 -3 -6 -1 -8 -7]
 [-5  4  1 -2  2 -5  4  0]
 [ 7  5  4  7  3  3  4 -1]]


### 6. Linear Algebra

Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [69]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[ 2  8 10]
 [ 1 10  5]
 [ 2  3  3]]
Determinant: -83.99999999999999
Inverse:
[[-0.17857143 -0.07142857  0.71428571]
 [-0.08333333  0.16666667  0.        ]
 [ 0.20238095 -0.11904762 -0.14285714]]
Eigenvalues: [13.58836947 -1.87874124  3.29037177]


Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[ 7  4  7]
 [ 2 10  9]]
Array 2:
[[ 7  1]
 [10  6]
 [ 2  6]]
Matrix multiplication result:
[[103  73]
 [132 116]]


### 7. Advanced Array Manipulation

Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [73]:
# using the array.reshape() function twice
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# reshaping the array
reshaped_array_1 = array.reshape((1, 9))
print(reshaped_array_1)

reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Flatten and unflatten an array

In [77]:

array = np.arange(1,21).reshape(4,5)
print("Original array:")
print(array)

print("Flattened array:")
print(array.flatten())


print("Reshaped array:")
print(array.reshape(4,5))


print("Reshaped array:")
print(array.reshape(5,4))


print("Reshaped array:")
print(array.reshape(10,2))



Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Reshaped array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


### 8. Fancy Indexing and Boolean Indexing

Use fancy indexing to extract the elements at the corners of an array.

In [83]:
array = np.arange(1, 31, 2).reshape(3,5)
print("Original array:")
print(array)

# fancy indexing is array[[x1,x2,x3],[y1,y2,y3]] to return (x1,y1), (x2,y2) etc indices
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
Corner elements:
[ 1  9 21 29]


Use boolean indexing to set all elements between 4 and 10 to 0 in an array.  
### V IMPORTANT

In [ ]:
# -------------------------------------------------------------
# NumPy Boolean Indexing Gotcha:
# 
# Example:
#   array[(array >= 5) & (array < 10)] = 0
#
# Explanation:
# 1. array >= 5  → returns a **boolean array** for each element
# 2. array < 10  → returns another **boolean array**
#
# ❌ Using 'and' between these arrays doesn't work:
#    - Python's 'and' expects **single boolean values**, not arrays
#    - Trying: array >= 5 and array < 10 
#      raises: ValueError: "The truth value of an array is ambiguous"
# 
# ✅ ✅ ✅ ✅ ✅  Correct approach: use '&' for **element-wise AND** ✅ ✅ ✅ ✅ ✅ ✅
#    - Parentheses are required: (array >= 5) & (array < 10)
#    - Without parentheses, operator precedence breaks it
#
# Why parentheses are required:
#    - '&' has **lower precedence** than comparison operators
#    - Writing array >= 5 & array < 10 would be evaluated as:
#          array >= (5 & array) < 10
#      which is incorrect
#
# Note: In normal Python 'if' statements:
#    - 'and' works on single booleans (True/False)
#    - No need for parentheses unless clarifying precedence
# -------------------------------------------------------------

array = np.arange(1, 16).reshape(3, 5)
print("Original array:")
print(array)

# simple conditional expression filters the array elements, and then assigning them new value
# and → works for single bool
# & → element-wise logical AND for arrays
array[(array >= 5) & (array <10) ] = 0
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Modified array:
[[ 1  2  3  4  0]
 [ 0  0  0  0 10]
 [11 12 13 14 15]]


### 9. Structured Arrays

Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

### VERY IMPORTANT

In [ ]:
# -------------------------------------------------------------
# Structured NumPy Array Example
#
# 1. 'data_type' defines the **dtype for each field**:
#    - 'name'   : 'U10' → Unicode string of max length 10
#    - 'age'    : 'i4'  → 4-byte integer
#    - 'weight' : 'f4'  → 4-byte float
#
# 2. 'data' is a **structured array** where each element is like a row
#    with named fields (name, age, weight).
#
# 3. This allows you to access columns by name:
#       data['name']   → array(['Alice', 'Bob', 'Charlie'], dtype='<U10')
#       data['age']    → array([25, 30, 20], dtype=int32)
#       data['weight'] → array([55.5, 85.3, 65.2], dtype=float32)
#
# Structured arrays are like a hybrid of arrays and records:
# you can index like an array or access fields by name.
# -------------------------------------------------------------
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25.9, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [98]:
# -------------------------------------------------------------
# Structured Array Example with Euclidean Distance
#
# 1️.  Create a structured array:
#    - 'data_type' defines fields: 'x' and 'y' as 4-byte integers
#    - 'data' stores each point as a tuple (x, y)
#
#       data = [(1,2), (3,4), (5,6)]
#       Access x-coordinates: data['x'] → [1 3 5]
#       Access y-coordinates: data['y'] → [2 4 6]
#
# 2️.   Compute Euclidean distance between all pairs of points:
#    - data['x'][:, np.newaxis] reshapes x-coords from (3,) → (3,1)
#      so broadcasting works for pairwise differences
#    - (data['x'][:, np.newaxis] - data['x'])**2 computes (x_i - x_j)^2 for all i,j
#    - Similarly for y: (data['y'][:, np.newaxis] - data['y'])**2
#    - np.sqrt(...) gives the Euclidean distance
#
# 3️.   Result:
#    distances[i,j] is the distance between point i and point j
#
# Example output:
# Original array:
# [(1, 2) (3, 4) (5, 6)]
#
# Euclidean distances:
# [[0.         2.828427  5.656854]
#  [2.828427  0.         2.828427]
#  [5.656854  2.828427  0.      ]]
#
# Notes:
# - Using structured arrays lets you access coordinates by name (data['x'], data['y'])
# - np.newaxis is used to **broadcast** arrays for pairwise operations
# -------------------------------------------------------------

data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### 10. Masked Arrays

Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [99]:
# -------------------------------------------------------------
# NumPy Masked Arrays Example
#
# 1️⃣ What is a masked array?
#    - A masked array is a NumPy array that can **ignore certain elements** 
#      in computations without actually removing them.
#    - The "mask" marks which elements are **invalid or should be ignored**.
#    - This is useful when working with missing data, filtering, or ignoring outliers.
#
# 2️⃣ Creating the array:
#    - array = np.random.randint(1, 21, size=(4, 4)) → random integers 1 to 20
#    - masked_array = ma.masked_greater(array, 10)
#       - This **masks all elements greater than 10**
#       - Masked elements are ignored in computations like sum, mean, etc.
#
# 3️⃣ Example behavior:
#    Original array (random):
#    [[ 5 12  3 14]
#     [10  9 16  7]
#     [ 8 15  2 11]
#     [ 1 13  6  4]]
#
#    Masked array (elements >10 masked):
#    [[5 -- 3 --]
#     [10 9 -- 7]
#     [8 -- 2 --]
#     [1 -- 6 4]]
#    ('--' indicates masked/ignored elements)
#
# 4️⃣ Computations ignore masked elements:
#    - sum_unmasked = masked_array.sum() → sums only elements ≤10
#      (masked elements do not contribute)
#
# 5️⃣ Key Points:
#    - masked_array.mask → Boolean array showing which elements are masked
#    - masked_array.data → original underlying data
#    - Operations like sum(), mean() automatically **skip masked elements**
# -------------------------------------------------------------
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[12 10  7  9]
 [ 4  5  1  2]
 [18  7  8 20]
 [11  2  4 18]]
Masked array:
[[-- 10 7 9]
 [4 5 1 2]
 [-- 7 8 --]
 [-- 2 4 --]]
Sum of unmasked elements: 59


Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
# -------------------------------------------------------------
# NumPy Masked Array with Custom Mask
#
# 1️⃣ array: the original data array, e.g., shape (3,3) or larger
#
# 2️⃣ Mask: np.eye(3, dtype=bool)
#    - np.eye(3) creates a 3x3 identity matrix:
#          [[1, 0, 0],
#           [0, 1, 0],
#           [0, 0, 1]]
#    - dtype=bool converts 1 → True, 0 → False
#          [[True, False, False],
#           [False, True, False],
#           [False, False, True]]
#    - True values indicate **masked/ignored elements**
#      False values are kept.
#
# 3️⃣ Create masked array:
#    masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
#    - The **diagonal elements** of 'array' will be masked
#    - Off-diagonal elements remain unmasked
#
#
#    Computations:
#    - masked_array.sum() → sums only **unmasked elements**
#    - masked_array.mean() → ignores masked elements automatically
#
# 
#    You can create **any custom mask** using a Boolean array of the same shape
#    True → mask/ignore, False → keep
# -------------------------------------------------------------
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 7  6  2]
 [ 5  3  6]
 [ 9  1 13]]
Masked array:
[[-- 6 2]
 [5 -- 6]
 [9 1 --]]
Modified masked array:
[[4 6 2]
 [5 4 6]
 [9 1 4]]
